GRAPHQL http://localhost:8000/graphql

query order {
    order(id: "9853bca0-d917-4218-a165-ae24b7489af0") {
      id
      userId
      orderItems {
        id
        salesItemId
        quantity
      }
    }
}

###
GRAPHQL http://localhost:8000/graphql

mutation createOrder {
    createOrder(inputOrder: { userId: "9853bca0-d917-4218-a165-ae24b7489af1", orderItems: [{ id: "9853bca0-d917-4218-a165-ae24b7489af2", salesItemId: "9853bca0-d917-4218-a165-ae24b7489af3", quantity: 100 }]}) {
      id
      userId
      orderItems {
        id
        salesItemId
        quantity
      }
    }
}

###