from typing import Annotated

from annotated_types import Len
from pydantic import BaseModel, Field

from .OrderItem import OrderItem


# Input DTOs declare the structure and validations for
# input from clients
# Below, we don't declare the 'id' field because it is
# generated by the server
# We also declare the maximum size for 'userId' to be 36
# characters and that there can be a maximum of 500
# order items in a single order
class InputOrder(BaseModel):
    userId: str = Field(max_length=36)
    orderItems: Annotated[list[OrderItem], Len(max_length=500)]
